#include "build.h"
#include "discover.h"
#include "error.h"
#include "folder_util.h"
#include "memory_util.h"
#include "minctes.h"
#include "minctes_util.h"
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <sys/syslimits.h>

#define MINCTES_MAIN_C_FILE_NAME "minctes_main.g.c"
#define MINCTES_TEST_RUNNER_FILE_NAME "test_runner"

static Error
discover_tests_in_discover_output(const FolderPath *output_folder_path,
                                  Slice *test_name_slice) {
  Error err = ERROR_NONE;
  if (test_name_slice->size_of_type != sizeof(char) * MAX_TEST_NAME_LENGTH) {
    return ERROR_INVALID_PARAM;
  }

  FilePath discovered_tests_file_path;
  err = file_path_init(&discovered_tests_file_path, output_folder_path,
                       DISCOVERED_TESTS_HEADER_FILE_NAME);
  if (err != ERROR_NONE) {
    return err;
  }

  FILE *discovered_tests_file =
      file_path_fopen(&discovered_tests_file_path, "r");
  if (discovered_tests_file == NULL) {
    return ERROR_COULD_NOT_OPEN_FILE;
  }

  minctes_util_tests_in_file(discovered_tests_file, test_name_slice,
                             TEST_IN_FILE_PREFIX_TYPE_PROCESSED);

  fclose(discovered_tests_file);
  return err;
}

static Error write_output_to_minctes_main_c(const FilePath *main_c_file_path,
                                            const Slice *test_name_slice) {
  Error err = ERROR_NONE;
  if (test_name_slice->size_of_type != sizeof(char) * MAX_TEST_NAME_LENGTH) {
    return ERROR_INVALID_PARAM;
  }

  FILE *output_file = file_path_fopen(main_c_file_path, "w");
  if (output_file == NULL) {
    return ERROR_COULD_NOT_OPEN_FILE;
  }

  if (fprintf(output_file,
              "/*--- FILE GENERATED BY MINCTES. DO NOT MODIFY. ---*/\n\n"
              "#include \"%s\"\n\n"
              "int main(){\n"
              // TODO should probably be safe malloced
              "\tMinctesRunner mr;\n"
              "\tminctes_runner_init(&mr);\n\n",
              DISCOVERED_TESTS_HEADER_FILE_NAME) < 0) {
    err = ERROR_COULD_NOT_WRITE_TO_FILE;
    goto close_output_file;
  }

  char buffer[MAX_TEST_NAME_LENGTH] = {0};
  for (size_t i = 0; i < test_name_slice->write_head; i++) {
    memset(buffer, 0, sizeof(char) * MAX_TEST_NAME_LENGTH);
    memcpy(buffer, "minctes_register_", strlen("minctes_register_"));
    strcat(buffer, (char *)slice_get(test_name_slice, i));
    // TODO this should not be as hard coded - will desync if macro is changed
    if (fprintf(output_file, "\t%s(&mr);\n", buffer) < 0) {
      err = ERROR_COULD_NOT_WRITE_TO_FILE;
      goto close_output_file;
    };
  }

  if (fprintf(output_file, "}\n") < 0) {
    err = ERROR_COULD_NOT_WRITE_TO_FILE;
    goto close_output_file;
  }

close_output_file:
  fclose(output_file);
  return err;
}

static Error create_minctes_main_c(const FolderPath *output_folder_path) {
  Error err = ERROR_NONE;

  FilePath main_c_file_path;
  /*We don't check error here as the file might not exist yet */
  file_path_init(&main_c_file_path, output_folder_path,
                 MINCTES_MAIN_C_FILE_NAME);

  Slice test_name_slice;
  slice_init(&test_name_slice, &ALLOCATOR_STDLIB,
             sizeof(char) * MAX_TEST_NAME_LENGTH, 1);
  err = discover_tests_in_discover_output(output_folder_path, &test_name_slice);
  if (err != ERROR_NONE) {
    goto free_test_name_slice;
  }

  err = write_output_to_minctes_main_c(&main_c_file_path, &test_name_slice);
  if (err != ERROR_NONE) {
    goto free_test_name_slice;
  }

free_test_name_slice:
  slice_free_data(&test_name_slice, &ALLOCATOR_STDLIB);
  return err;
}

static Error append_to_build_cmd_slice(Slice *build_cmd_slice,
                                       const char *str) {
  if (build_cmd_slice->size_of_type != sizeof(char)) {
    return ERROR_INVALID_PARAM;
  }
  slice_add(build_cmd_slice, &ALLOCATOR_STDLIB, " ");
  size_t len = strlen(str);
  char char_buffer;
  for (size_t i = 0; i < len; i++) {
    char_buffer = str[i];
    slice_add(build_cmd_slice, &ALLOCATOR_STDLIB, &char_buffer);
  }
  return ERROR_NONE;
}

static Error compile_build_runner(const FilePath *library_file_path,
                                  const FolderPath *output_folder) {
  (void)library_file_path;
  Error err = ERROR_NONE;
  Slice build_cmd_slice;
  slice_init(&build_cmd_slice, &ALLOCATOR_STDLIB, sizeof(char), 10);
  //TODO can't have this hard coded to clang
  err = append_to_build_cmd_slice(&build_cmd_slice, "clang");
  if (err != ERROR_NONE) {
    goto free_cmd_slice;
  }

  FilePath discovered_tests_directory_file_path;
  err = file_path_init(&discovered_tests_directory_file_path, output_folder,
                       DISCOVERED_TESTS_DIRECTORY_FILE_NAME);
  if (err != ERROR_NONE) {
    goto free_cmd_slice;
  }
  FILE *discovered_tests_directory_file =
      file_path_fopen(&discovered_tests_directory_file_path, "r");
  if (discovered_tests_directory_file == NULL) {
    err = ERROR_COULD_NOT_OPEN_FILE;
    goto free_cmd_slice;
  }

  char test_file_path_buffer[PATH_MAX];
  while (fscanf(discovered_tests_directory_file, "%s", test_file_path_buffer) ==
         true) {
    err = append_to_build_cmd_slice(&build_cmd_slice, test_file_path_buffer);
    if (err != ERROR_NONE) {
      goto close_discovered_tests_directory_file;
    }
  }

close_discovered_tests_directory_file:
  fclose(discovered_tests_directory_file);
free_cmd_slice:
  slice_free_data(&build_cmd_slice, &ALLOCATOR_STDLIB);
  return err;
}

Error minctes_build(const Compiler c_compiler,
                    const FilePath *library_file_path,
                    const FolderPath *output_folder) {
  (void)c_compiler;
  (void)library_file_path;
  Error err = ERROR_NONE;
  err = create_minctes_main_c(output_folder);
  if (err != ERROR_NONE) {
    return err;
  }
  err = compile_build_runner(library_file_path, output_folder);
  return err;
}
