#include "build.h"
#include "discover.h"
#include "error.h"
#include "folder_util.h"
#include <stdio.h>
#include <sys/syslimits.h>

#define MINCTES_MAIN_C_FILE_NAME "minctes_main.g.c"

static Error write_output_to_minctes_main_c(const FilePath *main_c_file_path) {
  Error err = ERROR_NONE;

  FILE *output_file = file_path_fopen(main_c_file_path, "w");
  if (output_file == NULL) {
    return ERROR_COULD_NOT_OPEN_FILE;
  }

  if (fprintf(output_file,
              "/*--- FILE GENERATED BY MINCTES. DO NOT MODIFY. ---*/\n\n"
              "#include \"minctes.h\"\n"
              "#include \"%s\"\n\n"
              "int main(){\n"
              // TODO add test functions
              "\t\n"
              "}\n",
              DISCOVERED_TESTS_FILE_NAME) < 0) {
    err = ERROR_COULD_NOT_WRITE_TO_FILE;
    goto close_output_file;
  }

close_output_file:
  fclose(output_file);
  return err;
}

static Error create_minctes_main_c(const FolderPath *output_folder_path) {
  Error err = ERROR_NONE;

  FilePath main_c_file_path;
  /*We don't check error here as the file might not exist yet */
  file_path_init(&main_c_file_path, output_folder_path,
                 MINCTES_MAIN_C_FILE_NAME);

  err = write_output_to_minctes_main_c(&main_c_file_path);
  if (err != ERROR_NONE) {
    return err;
  }

  return err;
}

Error minctes_build(const char *c_compiler, const FilePath *library_file_path,
                    const FolderPath *output_folder) {
  (void)c_compiler;
  (void)library_file_path;
  Error err = ERROR_NONE;
  err = create_minctes_main_c(output_folder);
  if (err != ERROR_NONE) {
    return err;
  }
  // compile_build_runner(c_compiler, test_files.c, library, output)
  return err;
}
