#include "discover.h"

#include "compiler.h"
#include "error.h"
#include "folder_util.h"
#include "memory_util.h"
#include "minctes.h"
#include "minctes_util.h"
#include <dirent.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/dirent.h>
#include <sys/syslimits.h>

#define TEST_FILE_EXTENSION ".t.c"
#define HEADER_EXTENSION ".h"

static Error discover_includes_in_file(const Compiler compiler,
                                       FilePath *file_path,
                                       Slice *includes_slice) {
  if (includes_slice->size_of_type != sizeof(char) * PATH_MAX) {
    return ERROR_INVALID_PARAM;
  }

  char file_path_buffer[PATH_MAX];
  file_path_as_cstring(file_path, file_path_buffer);

  char command_buffer[sizeof(compiler_include_commands[compiler]) + PATH_MAX];
// TODO not ideal, but fine for now
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-nonliteral"
  snprintf(command_buffer, sizeof(command_buffer),
           compiler_include_commands[compiler], file_path_buffer);
#pragma clang diagnostic pop

  FILE *pipe = popen(command_buffer, "r");
  if (pipe == NULL) {
    return ERROR_COULD_NOT_OPEN_FILE;
  }

  Error err = ERROR_NONE;
  char word_buffer[PATH_MAX];
  while (fscanf(pipe, "%s", word_buffer) == true) {
    /*This block of code has several objectives. First it removes line breaks in
     * output. Next, it filters out .x and .c files. It also removes main.o and
     * main.c at the start of the output*/
    const size_t header_extension_length = strlen(HEADER_EXTENSION);
    size_t word_length = strlen(word_buffer);
    if (word_length < header_extension_length ||
        strcmp(&word_buffer[word_length - header_extension_length],
               HEADER_EXTENSION) != 0) {
      continue;
    }

    char resolved[PATH_MAX];
    if (realpath(word_buffer, resolved) == NULL) {
      err = ERROR_UNRESOLVED_PATH;
      goto close_pipe;
    }
    slice_add(includes_slice, &ALLOCATOR_STDLIB, resolved);
  }

close_pipe:
  pclose(pipe);
  return err;
}

static bool file_path_is_test_file(const FilePath *self) {
  char buffer[PATH_MAX] = {0};
  file_path_as_cstring(self, buffer);

  size_t len = strlen(buffer);
  size_t extension_len = strlen(TEST_FILE_EXTENSION);

  if (len <= extension_len) {
    return false;
  }

  const char *ext = buffer + len - extension_len;
  return strcmp(ext, TEST_FILE_EXTENSION) == 0;
}

// TODO ADD RECURSION outside of this function
static Error find_test_files_in_folder(const FolderPath *source_folder,
                                       Slice *file_path_slice) {
  Error err = ERROR_NONE;
  if (file_path_slice->size_of_type != sizeof(FilePath)) {
    return ERROR_INVALID_PARAM;
  }
  char folder_path_buffer[PATH_MAX] = {0};
  folder_path_as_cstring(source_folder, folder_path_buffer);
  DIR *directory = opendir(folder_path_buffer);
  if (directory == NULL) {
    return ERROR_PATH_IS_NOT_FOLDER;
  }

  struct dirent *directory_entry_buffer;
  while ((directory_entry_buffer = readdir(directory)) != NULL) {
    if (directory_entry_buffer->d_type == DT_REG) {
      char file_name_buffer[FILENAME_MAX] = {0};
      memcpy(file_name_buffer, directory_entry_buffer->d_name,
             directory_entry_buffer->d_namlen);
      FilePath file_path;
      file_path_init(&file_path, source_folder, file_name_buffer);
      if (file_path_is_test_file(&file_path)) {
        slice_add(file_path_slice, &ALLOCATOR_STDLIB, &file_path);
      }
    }
  }

  closedir(directory);
  return err;
}

static Error add_header_to_output_file(FILE *output_file,
                                       Slice *includes_slice) {
  if (includes_slice->size_of_type != sizeof(char) * PATH_MAX) {
    return ERROR_INVALID_PARAM;
  }
  rewind(output_file);
  if (fprintf(output_file,
              "/*--- FILE GENERATED BY MINCTES. DO NOT MODIFY. ---*/\n"
              "#pragma once\n\n") < 0) {
    return ERROR_COULD_NOT_WRITE_TO_FILE;
  };

  for (size_t i = 0; i < includes_slice->write_head; i++) {
    if (fprintf(output_file, "#include \"%s\"\n",
                (char *)slice_get(includes_slice, i)) < 0) {
      return ERROR_COULD_NOT_WRITE_TO_FILE;
    }
  }

  if (fprintf(output_file, "\n") < 0) {
    return ERROR_COULD_NOT_WRITE_TO_FILE;
  }

  return ERROR_NONE;
}

static Error add_main_func_to_output_file(FILE *output_file,
                                          const Slice *test_name_slice) {
  Error err = ERROR_NONE;
  if (test_name_slice->size_of_type != sizeof(char) * MAX_TEST_NAME_LENGTH) {
    return ERROR_INVALID_PARAM;
  }

  char buffer[MAX_TEST_NAME_LENGTH] = {0};
  for (size_t i = 0; i < test_name_slice->write_head; i++) {
    memset(buffer, 0, sizeof(char) * MAX_TEST_NAME_LENGTH);
    memcpy(buffer, "minctes_register_", strlen("minctes_register_"));
    strcat(buffer, (char *)slice_get(test_name_slice, i));
    // TODO this should not be as hard coded - will desync if macro is changed
    if (fprintf(output_file, "void %s(MinctesRunner *mr);\n", buffer) < 0) {
      return ERROR_COULD_NOT_WRITE_TO_FILE;
    };
  }

  return err;
}

Error minctes_discover(const Compiler compiler, const FolderPath *source_folder,
                       const FolderPath *output_folder) {
  Error err = ERROR_NONE;

  Slice test_file_path_slice;
  slice_init(&test_file_path_slice, &ALLOCATOR_STDLIB, sizeof(FilePath), 1);
  err = find_test_files_in_folder(source_folder, &test_file_path_slice);
  if (err != ERROR_NONE) {
    goto free_test_file_path_slice;
  }

  Slice test_name_slice;
  slice_init(&test_name_slice, &ALLOCATOR_STDLIB,
             MAX_TEST_NAME_LENGTH * sizeof(char), 1);
  Slice includes_slice;
  slice_init(&includes_slice, &ALLOCATOR_STDLIB, PATH_MAX * sizeof(char), 1);

  FilePath *file_paths = test_file_path_slice.data;
  for (size_t i = 0; i < test_file_path_slice.write_head; i++) {
    FILE *file = file_path_fopen(&file_paths[i], "r");
    if (file == NULL) {
      err = ERROR_COULD_NOT_OPEN_FILE;
      goto free_discovery_slices;
    }

    discover_includes_in_file(compiler, &file_paths[i], &includes_slice);
    minctes_util_tests_in_file(file, &test_name_slice,
                               TEST_IN_FILE_PREFIX_TYPE_UNPROCESSED);
    fclose(file);
  }

  FilePath output_file_path;
  file_path_init(&output_file_path, output_folder, DISCOVERED_TESTS_FILE_NAME);
  FILE *output_file = file_path_fopen(&output_file_path, "w");
  if (output_file == NULL) {
    err = ERROR_COULD_NOT_OPEN_FILE;
    goto free_discovery_slices;
  }

  err = add_header_to_output_file(output_file, &includes_slice);
  if (err != ERROR_NONE) {
    goto close_output_file;
  }

  err = add_main_func_to_output_file(output_file, &test_name_slice);
  if (err != ERROR_NONE) {
    goto close_output_file;
  }

close_output_file:
  fclose(output_file);
free_discovery_slices:
  slice_free_data(&includes_slice, &ALLOCATOR_STDLIB);
  slice_free_data(&test_name_slice, &ALLOCATOR_STDLIB);
free_test_file_path_slice:
  slice_free_data(&test_file_path_slice, &ALLOCATOR_STDLIB);
  return err;
}
