#include "discover.h"

#include <dirent.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <sys/dirent.h>
#include <sys/syslimits.h>

#include "error.h"
#include "folder_util.h"
#include "memory_util.h"
#include "minctes.h"

#define TEST_FILE_EXTENSION ".t.c"
#define OUTPUT_FILE_NAME "discovered_tests.g.h"

static bool file_path_is_test_file(const FilePath *self) {
  char buffer[PATH_MAX + FILENAME_MAX] = {0};
  file_path_as_cstring(self, buffer);

  size_t len = strlen(buffer);
  size_t extension_len = strlen(TEST_FILE_EXTENSION);

  if (len <= extension_len) {
    return false;
  }

  const char *ext = buffer + len - extension_len;
  return strcmp(ext, TEST_FILE_EXTENSION) == 0;
}

// TODO ADD RECURSION outside of this function
static Error find_test_files_in_folder(const FolderPath *source_folder,
                                       Slice *file_path_slice) {
  Error err = ERROR_NONE;
  if (file_path_slice->size_of_type != sizeof(FilePath)) {
    return ERROR_INVALID_PARAM;
  }
  char folder_path_buffer[PATH_MAX] = {0};
  folder_path_as_cstring(source_folder, folder_path_buffer);
  DIR *directory = opendir(folder_path_buffer);
  if (directory == NULL) {
    return ERROR_PATH_IS_NOT_FOLDER;
  }

  struct dirent *directory_entry_buffer;
  while ((directory_entry_buffer = readdir(directory)) != NULL) {
    if (directory_entry_buffer->d_type == DT_REG) {
      char file_name_buffer[FILENAME_MAX] = {0};
      memcpy(file_name_buffer, directory_entry_buffer->d_name,
             directory_entry_buffer->d_namlen);
      FilePath file_path;
      file_path_init(&file_path, *source_folder, file_name_buffer);
      if (file_path_is_test_file(&file_path)) {
        slice_add(file_path_slice, &ALLOCATOR_STDLIB, &file_path);
      }
    }
  }

  closedir(directory);
  return err;
}

static void discover_tests_in_file(FILE *file, Slice *test_name_slice) {
  /*TODO: This could cause issues if someone puts the prefix in the middle of a
   * function name or comments. Also, in the future, it would be better to get
   * the c preprocessor to expand the test delaration, and then detect the
   * registration function name from the intermediate file. This would reduce
   * name collisions,as the expanded prefix could be more unique*/
  static const char prefix_length = strlen(minctes_registration_macro_prefix);
  char word[MAX_TEST_NAME_LENGTH];
  rewind(file);
  while (fscanf(file, "%s", word) == true) {
    if (strstr(word, minctes_registration_macro_prefix)) {
      char trimmed_name[MAX_TEST_NAME_LENGTH] = {0};
      size_t len = strlen(word);
      for (size_t i = 0; i < len; i++) {
        if (i < prefix_length) {
          continue;
        }
        if (word[i] == ')') {
          break;
        }
        trimmed_name[i - prefix_length] = word[i];
      }
      slice_add(test_name_slice, &ALLOCATOR_STDLIB, trimmed_name);
    }
  }
}

static Error add_header_to_output_file(FILE *output_file) {
  if (fprintf(output_file,
              "/*--- FILE GENERATED BY MINCTES. DO NOT MODIFY. ---*/\n"
              "#pragma once\n\n"
              "#include \"minctes.h\"\n\n") < 0) {
    return ERROR_COULD_NOT_WRITE_TO_FILE;
  };
  return ERROR_NONE;
}

static Error add_main_func_to_output_file(FILE *output_file,
                                          const Slice *test_name_slice) {
  Error err = ERROR_NONE;
  if (test_name_slice->size_of_type != sizeof(char) * MAX_TEST_NAME_LENGTH) {
    return ERROR_INVALID_PARAM;
  }

  // TODO this should not be as hardcoded
  // if (fprintf(output_file, "int main(){\n"
  //                          "\tMinctesRunner mr;\n"
  //                          "\tminctes_runner_init(&mr);\n") < 0) {
  //   return ERROR_COULD_NOT_WRITE_TO_FILE;
  // }

  char buffer[MAX_TEST_NAME_LENGTH] = {0};
  for (size_t i = 0; i < test_name_slice->write_head; i++) {
    memset(buffer, 0, sizeof(char) * MAX_TEST_NAME_LENGTH);
    memcpy(buffer, "minctes_register_", strlen("minctes_register_"));
    strcat(buffer, (char *)slice_get(test_name_slice, i));
    // TODO this should not be as hard coded - will desync if macro is changed
    if (fprintf(output_file, "void %s(MinctesRunner *mr);\n", buffer) < 0) {
      return ERROR_COULD_NOT_WRITE_TO_FILE;
    };
  }

  // if (fprintf(output_file, "}\n") < 0) {
  //   return ERROR_COULD_NOT_WRITE_TO_FILE;
  // }
  return err;
}

Error minctes_discover(const FolderPath *source_folder,
                       const FolderPath *output_folder) {
  (void)output_folder;
  Error err = ERROR_NONE;

  Slice test_file_path_slice;
  slice_init(&test_file_path_slice, &ALLOCATOR_STDLIB, sizeof(FilePath), 1);
  err = find_test_files_in_folder(source_folder, &test_file_path_slice);
  if (err != ERROR_NONE) {
    goto free_test_file_path_slice;
  }

  Slice test_name_slice;
  slice_init(&test_name_slice, &ALLOCATOR_STDLIB,
             MAX_TEST_NAME_LENGTH * sizeof(char), 1);

  for (size_t i = 0; i < test_file_path_slice.write_head; i++) {
    FilePath *file_paths = test_file_path_slice.data;
    char file_path_buffer[PATH_MAX + FILENAME_MAX] = {0};
    file_path_as_cstring(&file_paths[i], file_path_buffer);

    FILE *file = fopen(file_path_buffer, "r");
    if (file == NULL) {
      err = ERROR_COULD_NOT_OPEN_FILE;
      goto free_test_name_slice;
    }

    // TODO
    //  discover_includes_in_file(file, &)
    discover_tests_in_file(file, &test_name_slice);
    fclose(file);
  }

  char output_file_path_buffer[PATH_MAX] = {0};
  folder_path_as_cstring(output_folder, output_file_path_buffer);
  size_t len = strlen(output_file_path_buffer);
  snprintf(output_file_path_buffer + len, sizeof(output_file_path_buffer) - len,
           "/%s", OUTPUT_FILE_NAME);
  FILE *output_file = fopen(output_file_path_buffer, "w");
  if (output_file == NULL) {
    err = ERROR_COULD_NOT_OPEN_FILE;
    goto free_test_name_slice;
  }

  err = add_header_to_output_file(output_file);
  if (err != ERROR_NONE) {
    goto close_output_file;
  }

  err = add_main_func_to_output_file(output_file, &test_name_slice);
  if (err != ERROR_NONE) {
    goto close_output_file;
  }

close_output_file:
  fclose(output_file);
free_test_name_slice:
  slice_free_data(&test_name_slice, &ALLOCATOR_STDLIB);
free_test_file_path_slice:
  slice_free_data(&test_file_path_slice, &ALLOCATOR_STDLIB);
  return err;
}
