X(NONE, Success)
X(UNKNOWN, An unknown error has occoured)
X(UNIMPLEMENTED, Requested program is unimplemented)
X(UNKNOWN_PROGRAM, The requested program does not exist)
X(TOO_MANY_TESTS, Exceeded the maximum number of tests)
X(PATH_IS_NOT_FOLDER, The provided path does not resolve to a folder)
X(OUT_OF_MEMORY, Failed to allocate enough memory - is your ram full?)
X(INVALID_PARAM, Function called with invalid param)
X(PATH_IS_NOT_FILE, The provided path does not resolve to a regular file)
