X(NONE, Success)
X(UNKNOWN, An unknown error has occoured)
X(UNIMPLEMENTED, Requested program is unimplemented)
X(UNKNOWN_PROGRAM, The requested program does not exist)
X(TOO_MANY_TESTS, Exceeded the maximum number of tests)
